"""
Descriptive overview figure for measured generic- and specific-SAE results.

Panel A: DAMS score (Generic SAE vs Best Domain-Specific SAE) vs CLIP FID
Panel B: Concept-space accuracy drop (LoRA + Generic SAE vs bare LoRA-FT)
         for 8 datasets, ordered by CLIP FID

The confirmatory MMD predictor and its held-out predictions are generated by
the rebuttal predictor workflow, not by fitting a flexible curve in this
descriptive plotting script.
"""

import json, os
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec

matplotlib.use("Agg")
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 10,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "figure.dpi": 150,
})

OUT_DIR = "/home/sunayana/Documents/Concept_LoRA/figures"
os.makedirs(OUT_DIR, exist_ok=True)

# ── Data ───────────────────────────────────────────────────────────────────────

# CLIP FID from our computed distance_results.csv (primary domain-shift axis)
dist = pd.read_csv("/home/sunayana/Documents/Concept_LoRA/distance_results.csv")
dist = dist[dist.dataset != "**imagenet_split_half**"]
fid_map = dict(zip(dist.dataset, dist.FID_clip))
mmd_map = dict(zip(dist.dataset, dist.MMD2_clip))

# Dataset name normalisation
DS_NORM = {
    "caltech101": "caltech-101",
    "eurosat":    "eurosat",
    "medmnist":   "pathmnist",
    "cub2002011": "cub200",
    "dtd":        "dtd",
    "ucf101":     "UCF101",
}
DS_LABEL = {
    "caltech-101": "Caltech-101",
    "eurosat":     "EuroSAT",
    "pathmnist":   "MedMNIST",
    "cub200":      "CUB-200",
    "dtd":         "DTD",
    "UCF101":      "UCF-101",
    "fgvc":        "FGVC",
    "oxford_pets": "OxfordPets",
}

# DAMS values from the fixed-configuration evaluation export.  Do not choose a
# sweep row using the same outcome later plotted as evidence.
with open("/home/sunayana/Documents/Concept_LoRA/sae_vlm/out/sae_dams_results.json") as f:
    dams_raw = json.load(f)

dams_data = {}
for row in dams_raw:
    ds_norm = DS_NORM.get(row["dataset"], row["dataset"])
    fid = fid_map.get(ds_norm, np.nan)
    if not np.isfinite(fid):
        continue
    values = dams_data.setdefault(
        ds_norm,
        {
            "base": np.nan,
            "lora": np.nan,
            "fid": fid,
            "label": DS_LABEL.get(ds_norm, ds_norm),
        },
    )
    if row["name"] == "Base SAE":
        values["base"] = row["dams"]
    elif row["name"] == "LoRA SAE":
        values["lora"] = row["dams"]

dams_data = {
    ds: values
    for ds, values in dams_data.items()
    if np.isfinite(values["base"])
}

# Concept accuracy from sae_concept_accuracy.json
with open("/home/sunayana/Documents/Concept_LoRA/results/sae_concept_accuracy.json") as f:
    concept_raw = json.load(f)

concept_data = {}
for row in concept_raw:
    ds = row["dataset"]
    ds_norm = DS_NORM.get(ds, ds)
    fid = fid_map.get(ds_norm, np.nan)
    concept_data[ds_norm] = {
        "lora_acc":         row["LoRA-FT"],
        "lora_concept_acc": row["LoRA+SAE-concept"],
        "delta":            row["delta_LoRA_concept"],   # negative = accuracy drop
        "fid":              fid,
        "label":            DS_LABEL.get(ds_norm, ds),
    }
# Never substitute hand-entered domain-distance estimates.  A missing distance
# means that dataset is omitted until compute_distances.py (or the held-out
# predictor's cache-only distance stage) has produced a measured value under
# the same extractor and estimator as every other point.
missing_fid = sorted(
    ds for ds, values in concept_data.items()
    if not np.isfinite(values["fid"])
)
if missing_fid:
    print(
        "Omitting concept-accuracy rows without measured CLIP FID: "
        + ", ".join(missing_fid)
    )
concept_data = {
    ds: values for ds, values in concept_data.items()
    if np.isfinite(values["fid"])
}

# ── Tier coloring ──────────────────────────────────────────────────────────────
TIER_BOUNDS = [0.0, 0.05, 0.25, 0.45, 1.0]
TIER_COLORS = ["#2ecc71", "#3498db", "#e67e22", "#e74c3c"]
TIER_LABELS = ["Near-IID", "Low shift", "High shift", "OOD"]

def tier_color(fid):
    for i, (lo, hi) in enumerate(zip(TIER_BOUNDS[:-1], TIER_BOUNDS[1:])):
        if lo <= fid < hi:
            return TIER_COLORS[i]
    return TIER_COLORS[-1]

# ── Figure ─────────────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(13, 5.2))
gs  = GridSpec(1, 2, figure=fig, width_ratios=[1.15, 1], wspace=0.38)
ax1 = fig.add_subplot(gs[0])
ax2 = fig.add_subplot(gs[1])

# ── Panel A: DAMS vs CLIP FID ──────────────────────────────────────────────────
base_fids, base_scores, lora_fids, lora_scores = [], [], [], []

for ds, vals in sorted(dams_data.items(), key=lambda x: x[1]["fid"]):
    fid   = vals["fid"]
    color = tier_color(fid)
    base_scores.append(vals["base"])
    base_fids.append(fid)
    ax1.scatter(fid, vals["base"], color=color, s=90, zorder=4,
                marker="o", edgecolors="white", linewidth=0.8)

    if not np.isnan(vals["lora"]):
        lora_scores.append(vals["lora"])
        lora_fids.append(fid)
        ax1.scatter(fid, vals["lora"], color=color, s=90, zorder=4,
                    marker="^", edgecolors="white", linewidth=0.8)
        # Vertical arrow showing the gap
        ax1.annotate("", xy=(fid, vals["lora"]), xytext=(fid, vals["base"]),
                     arrowprops=dict(arrowstyle="->" if vals["lora"] > vals["base"] else "-",
                                     color=color, lw=1.4, alpha=0.6))
    # Dataset label
    y_offset = 0.02 if vals.get("lora", 0) > vals["base"] else -0.04
    label_y  = max(vals["base"], vals.get("lora", vals["base"])) + 0.03
    ax1.text(fid + 0.005, label_y, vals["label"],
             fontsize=7.5, color="black", va="bottom", ha="left")

# Legend handles
legend_elems = [
    plt.scatter([], [], marker="o", color="grey", s=60,
                edgecolors="white", label="Generic SAE"),
    plt.scatter([], [], marker="^", color="grey", s=60,
                edgecolors="white", label="Domain-Specific SAE"),
]
tier_patches = [mpatches.Patch(color=TIER_COLORS[i], label=TIER_LABELS[i], alpha=0.8)
                for i in range(len(TIER_LABELS))]
ax1.legend(handles=legend_elems + tier_patches,
           fontsize=8, loc="upper left", framealpha=0.9,
           ncol=2, columnspacing=0.8)

ax1.set_xlabel("CLIP FID (domain distance from ImageNet)", labelpad=6)
ax1.set_ylabel("Domain-Aware Monosemanticity Score (DAMS)", labelpad=6)
ax1.set_title("A   Measured DAMS by SAE arm and domain distance",
              loc="left", fontweight="bold", fontsize=10.5, pad=8)
ax1.set_xlim(0.05, 0.82)
ax1.set_ylim(-0.02, 1.0)
ax1.axhline(0, color="grey", lw=0.5, ls=":")
# ── Panel B: Concept accuracy drop vs CLIP FID ────────────────────────────────
cd_sorted = sorted(concept_data.values(), key=lambda x: x["fid"])

xs       = [d["fid"]   for d in cd_sorted]
deltas   = [-d["delta"] for d in cd_sorted]   # make positive = drop
labels   = [d["label"] for d in cd_sorted]
colors_b = [tier_color(x) for x in xs]

bars = ax2.barh(range(len(xs)), deltas, color=colors_b, alpha=0.82,
                edgecolor="white", height=0.7)

# Annotate each bar with the absolute accuracy numbers
for i, d in enumerate(cd_sorted):
    drop = -d["delta"]
    ax2.text(drop + 0.5, i,
             f"LoRA-FT: {d['lora_acc']:.1f}%  →  Concept: {d['lora_concept_acc']:.1f}%",
             va="center", ha="left", fontsize=7.5, color="#555")

ax2.set_yticks(range(len(labels)))
ax2.set_yticklabels(labels, fontsize=9)
ax2.set_xlabel("Accuracy drop  LoRA-FT → LoRA + Generic SAE concept space  (pp)", labelpad=6)
ax2.set_title("B   Generic SAE concept space fails to preserve LoRA-FT accuracy",
              loc="left", fontweight="bold", fontsize=10.5, pad=8)
ax2.set_xlim(0, 80)

# Add CLIP FID annotations inside bars
for i, (x, d) in enumerate(zip(xs, cd_sorted)):
    ax2.text(0.8, i, f"FID={x:.2f}", va="center", ha="left",
             fontsize=7, color="white", fontweight="bold")

# Tier legend for panel B
ax2.legend(handles=tier_patches, fontsize=8, loc="lower right",
           framealpha=0.9, title="Domain shift tier")

# ── Global annotations ─────────────────────────────────────────────────────────
fig.text(0.5, -0.03,
         "Domain distance measured by CLIP ViT-L/14 FID against ImageNet-1k validation set.",
         ha="center", fontsize=8, color="grey", style="italic")

plt.savefig(os.path.join(OUT_DIR, "pitch_figure.pdf"),
            bbox_inches="tight", dpi=150)
plt.savefig(os.path.join(OUT_DIR, "pitch_figure.png"),
            bbox_inches="tight", dpi=180)
plt.close(fig)
print("Saved pitch_figure.{pdf,png} →", OUT_DIR)

# ── Print data table ───────────────────────────────────────────────────────────
print(f"\n{'='*70}")
print("Panel A — DAMS data")
print(f"{'Dataset':<14} {'CLIP FID':>9} {'Base DAMS':>10} {'LoRA DAMS':>10} {'Gap':>7}")
print("─"*55)
for ds, v in sorted(dams_data.items(), key=lambda x: x[1]["fid"]):
    gap = v["lora"] - v["base"] if not np.isnan(v.get("lora", np.nan)) else np.nan
    print(f"  {v['label']:<12} {v['fid']:>9.3f} {v['base']:>10.4f} "
          f"{v.get('lora', float('nan')):>10.4f} {gap:>7.4f}")

print(f"\n{'='*70}")
print("Panel B — Concept accuracy")
print(f"{'Dataset':<14} {'CLIP FID':>9} {'LoRA-FT':>8} {'Concept':>9} {'Drop (pp)':>10}")
print("─"*55)
for d in sorted(concept_data.values(), key=lambda x: x["fid"]):
    print(f"  {d['label']:<12} {d['fid']:>9.3f} {d['lora_acc']:>8.2f} "
          f"{d['lora_concept_acc']:>9.2f} {-d['delta']:>10.2f}")
