#!/usr/bin/env python3
"""Aggregate masking ablations across seeds and emit CSV + paper-ready LaTeX."""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


METRICS = ["accuracy", "recon_cosine", "fve", "l0", "dead_frac"]


def ci95(values):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    if len(values) < 2:
        return np.nan
    # Student-t critical values for the intended 3-seed design; normal
    # approximation beyond 30. Avoid a hard scipy dependency on cluster nodes.
    tcrit = {2: 12.706, 3: 4.303, 4: 3.182, 5: 2.776, 6: 2.571,
             7: 2.447, 8: 2.365, 9: 2.306, 10: 2.262}.get(len(values), 1.96)
    return tcrit * values.std(ddof=1) / np.sqrt(len(values))


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", default="out/masking_ablation/raw_results.csv")
    p.add_argument("--out_dir", default="out/masking_ablation")
    p.add_argument("--expected_seeds", type=int, default=3)
    args = p.parse_args()
    df = pd.read_csv(args.input)
    required = {"dataset", "training_seed", "protect_frac", "domain", *METRICS}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")
    duplicates = df.duplicated(["dataset", "training_seed", "protect_frac", "domain"])
    if duplicates.any():
        raise ValueError("Duplicate run/domain rows found; refusing to aggregate")
    counts = df.groupby(["dataset", "protect_frac", "domain"]).training_seed.nunique()
    incomplete = counts[counts != args.expected_seeds]
    if len(incomplete):
        raise ValueError("Incomplete cells (paper tables require exactly "
                         f"{args.expected_seeds} seeds):\n{incomplete}")
    keys = ["dataset", "protect_frac", "domain"]
    records = []
    for group_key, group in df.groupby(keys, sort=True):
        row = dict(zip(keys, group_key))
        row["n_seeds"] = group.training_seed.nunique()
        for metric in METRICS:
            row[f"{metric}_mean"] = group[metric].mean()
            row[f"{metric}_ci95"] = ci95(group[metric])
        records.append(row)
    summary = pd.DataFrame(records)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    summary.to_csv(out / "summary.csv", index=False)

    # One compact table per target dataset, reporting the central old/new-domain
    # trade-off. Other SAE metrics remain available in summary.csv.
    lines = ["% Auto-generated by tasks/summarize_masking_ablation.py"]
    for dataset, part in summary.groupby("dataset", sort=True):
        pivot = part.pivot(index="protect_frac", columns="domain")
        lines += [
            "\\begin{table}[t]", "\\centering", "\\small",
            f"\\caption{{Masking-percentage ablation on {dataset}. Mean $\\pm$ 95\\% CI over three training seeds; all other hyperparameters and evaluation images are fixed.}}",
            f"\\label{{tab:mask-ablation-{dataset}}}",
            "\\begin{tabular}{rcc}", "\\toprule",
            "Protected units & Target accuracy & ImageNet accuracy \\\\", "\\midrule",
        ]
        for frac in pivot.index:
            def cell(domain):
                mean = pivot.loc[frac, ("accuracy_mean", domain)]
                ci = pivot.loc[frac, ("accuracy_ci95", domain)]
                return f"{mean:.2f} $\\pm$ {ci:.2f}"
            lines.append(f"{100 * frac:.0f}\\% & {cell('target')} & {cell('imagenet')} \\\\")
        lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (out / "masking_ablation_tables.tex").write_text("\n".join(lines))
    print(f"Wrote {out / 'summary.csv'}")
    print(f"Wrote {out / 'masking_ablation_tables.tex'}")


if __name__ == "__main__":
    main()
